fix background on speed button #1145
breez/breezmobile pull request #1148
Opened 2023-05-22 18:18 UTC by ubbabeck

This is a fix for issue #1145 where the buttons had wrong colour.

2023-05-22 18:54 UTC, ubbabeck commented
https://github.com/breez/breezmobile/assets/36157890/7d4076f8-12e2-403f-b5e6-9082ef0b22a3

2023-05-22 20:33 UTC, erdemyerebasmaz requested changes
These values do work but they are likely to cause regressions in the future.

2023-05-22 20:35 UTC, erdemyerebasmaz commented on lib/routes/podcast/speed_selector.dart
> +            backgroundColor: themeData.dialogBackgroundColor,
```suggestion
            foregroundColor: themeData.buttonTheme.colorScheme.onPrimary,
            backgroundColor: themeData.scaffoldBackgroundColor,
```

2023-05-22 21:12 UTC, erdemyerebasmaz approved these changes

2023-05-23 06:06 UTC, roeierez approved these changes

2023-05-23 07:17 UTC, merged