WIP: Add payment options
breez/breezmobile pull request #787
Opened 2022-03-03 14:58 UTC by ademar111190

- Add the maximum fee payment can ask
Related: https://github.com/breez/breez/pull/152

2022-03-07 13:19 UTC, bitcoinuser commented on lib/l10n/app_pt.arb
> +  "payment_options_title": "Taxas da rede relâmpago",
```suggestion
  "payment_options_title": "Taxas da rede Relâmpago",
```

2022-03-07 13:20 UTC, bitcoinuser requested changes
Minor changes PT-BR

2022-03-07 13:42 UTC, tlindi requested changes
Fix Finnish

2022-03-07 13:42 UTC, tlindi commented on lib/l10n/app_fi.arb
> +  "home_drawer_item_title_payment_options": "Lightning Fees",
```suggestion
  "home_drawer_item_title_payment_options": "Salamamaksun kulut",
```

2022-03-07 13:42 UTC, tlindi commented on lib/l10n/app_fi.arb
> +  "payment_options_fee_action_save": "Save",
```suggestion
  "payment_options_title": "Salamamaksun kulut",
  "payment_options_fee_header": "Salamamaksujen hyväksyttävä enimmäiskulu:",
  "payment_options_base_fee_label": "Tapahtuman perusmaksu satosheina", 
  "payment_options_proportional_fee_label": "Tapahtuman määräpohjainen kulu (%)",
  "payment_options_fee_action_reset": "Nollaa",
  "payment_options_fee_action_save": "TALLENNA",
```

2022-03-07 16:41 UTC, roeierez approved these changes

2022-03-07 16:51 UTC, bitcoinuser commented on lib/l10n/app_pt.arb
> +  "home_drawer_item_title_payment_options": "Taxas da rede relâmpago",
```suggestion
  "home_drawer_item_title_payment_options": "Taxas de pagamento",
```

2022-03-07 16:53 UTC, bitcoinuser requested changes
Mudança no menu para o texto menor: Taxa de pagamento

2022-03-09 12:39 UTC, bitcoinuser commented on lib/l10n/app_pt.arb
> +  "payment_options_title": "Taxas de pagamento",
```suggestion
  "payment_options_title": "Taxas de Pagamento",
```

2022-03-09 12:39 UTC, bitcoinuser requested changes
Minor change

2022-03-09 12:42 UTC, bitcoinuser commented on lib/l10n/app_pt.arb
> +  "home_drawer_item_title_payment_options": "Taxas de pagamento",
```suggestion
  "home_drawer_item_title_payment_options": "Taxas de Pagamento",
```

2022-03-09 12:42 UTC, bitcoinuser requested changes
Minor change

2022-03-24 13:55 UTC, tlindi commented
Please amends change to app_fi.arb
-  "payment_options_fee_override_enable": "Enforce maximum fees for Lightning payments",
+ "payment_options_fee_override_enable": "Määritä Salamamaksujen hyväksyttävä enimmäiskulu",

2022-05-10 15:14 UTC, tlindi commented
app_fi.arb looks good

2022-05-10 20:23 UTC, merged