Add right sign currency support in currency converter
breez/breezmobile pull request #881
Opened 2022-04-12 13:57 UTC by ademar111190

Fixes https://github.com/breez/breezmobile/issues/760

How it looks like:

https://user-images.githubusercontent.com/1225438/163410546-289ec84a-b22f-4fd0-a523-79f7026e7dc8.mp4

2022-04-12 14:25 UTC, tlindi commented
TY 💯

2022-04-14 14:23 UTC, ademar111190 commented
I did apply the masking strategy, I did update the description with a video of what it looks like. please take a look @kingonly

2022-04-14 14:49 UTC, kingonly commented
@ademar111190 this is perfect!

2022-04-24 10:06 UTC, roeierez requested changes
Very nice!

2022-04-25 13:38 UTC, ademar111190 commented on lib/widgets/currency_amount_field_formatter.dart
> +        return oldValue;
You are right it is better, I did apply it.

2022-04-26 08:06 UTC, roeierez approved these changes

2022-04-26 12:30 UTC, merged