Playback Speed Range increased to 3*
breez/breezmobile pull request #889
Opened 2022-04-19 15:14 UTC by Sahilsingh0808

**Playback Speed Range increased**: The range of playback speed is set from 2.00 to 3.00 to give the user more freedom to choose their podcast streaming speed. The speed steps' remains 0.25 and the number of speed blocks are increased from 6 to 10.
![Screenshot_20220419_194841](https://user-images.githubusercontent.com/63606011/164037060-c5d67d8f-0d39-48b7-9aa9-056c76f39856.png)

![Screenshot_20220419_194939](https://user-images.githubusercontent.com/63606011/164037076-c3b0cec0-8de5-4552-a5b9-4f4a0b360ad5.png)

**Flutter Packages updated**: The packages from pub.dev have been updated to their latest version. These include a few packages that turned a few versions outdated in the meantime.

2022-04-24 10:19 UTC, roeierez approved these changes

2022-04-25 15:24 UTC, ademar111190 requested changes

2022-04-25 20:30 UTC, Sahilsingh0808 commented on pubspec.yaml
> +  build_runner: ^2.1.10
I have removed the updates from the yaml file now.
Thanks

2022-04-25 20:36 UTC, Sahilsingh0808 commented on pubspec.yaml
> +  build_runner: ^2.1.10
I have kept the yaml file as par with the current version of the original breezmobile repo.

2022-04-25 23:42 UTC, ademar111190 commented on pubspec.yaml
> +  build_runner: ^2.1.10
It is still in the diff for me

2022-04-26 01:15 UTC, Sahilsingh0808 commented on pubspec.yaml
> +  build_runner: ^2.1.10
Currently, my yaml file in the pull request is the same as the yaml file in the breezmobile repo. Should it be changed?

2022-04-26 12:38 UTC, ademar111190 commented on pubspec.yaml
> +  build_runner: ^2.1.10
It is not the same @Sahilsingh0808 take a look at the Files Changed tab.

2022-04-26 16:52 UTC, Sahilsingh0808 commented on pubspec.yaml
> +  build_runner: ^2.1.10
Shall I delete the file: pubspec.yaml from the pull request?

2022-04-26 16:53 UTC, kingonly commented on pubspec.yaml
> +  build_runner: ^2.1.10
I think it's better to delete it, yes

2022-04-26 16:56 UTC, Sahilsingh0808 commented on pubspec.yaml
> +  build_runner: ^2.1.10
Yes its done now

2022-04-26 18:15 UTC, merged